WebApplication1/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ApplicationController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Application> objList = _db.Application;
            return View(objList);
        }

        public IActionResult Create(int? id)
        {
            if (id != 0)
            {
                var updatingObj = _db.Application.Find(id);
                return View(updatingObj);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Application obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id != 0)
                {
                    _db.Application.Update(obj);
                }
                else
                {
                    _db.Application.Add(obj);
                }
                _db.SaveChanges();
            }
            return View();
        }
    }
}

WebApplication1/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        //--inti
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        #region Index
        public IActionResult Index()
        {
            IEnumerable<Category> objList = _db.Category;
            return View(objList);
        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion
        #region Update
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            else
            {
                Category category = _db.Category.Find(Id);
                return View(category);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            _db.Category.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion
        #region Delete
        public IActionResult Delete(int? Id)
        {
            Category obj = _db.Category.Find(Id);
            if (obj != null)
            {
                _db.Category.Remove(obj);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");

        }
        #endregion
    }
}

WebApplication1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Models.ViewModel;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _IWebHostEnviroment;

        //--inti
        public ProductController(ApplicationDbContext db, IWebHostEnvironment IWebHostEnviroment)
        {
            _db = db;
            _IWebHostEnviroment = IWebHostEnviroment;
        }
        #region Index
        public IActionResult Index()
        {
            IEnumerable<Product> objList = _db.Product.Include(u => u.Application).Include(u=>u.Category);
            //foreach (var obj in objList)
            //{
            //    if (obj.CategoryId != 0)
            //    {
            //        obj.Category = _db.Category.FirstOrDefault(u => u.Id == obj.CategoryId);
            //    }
            //}
            return View(objList);
        }
        #endregion
        #region Handle
        public IActionResult Handle(int? Id)
        {
            ProductVM productVM = new ProductVM()
            {
                Product = new Product(),
                CategoryDropDown = _db.Category.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                ApplicationDropDown = _db.Application.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            //查看是否帶PKID進入Handle頁面
            if (Id != null && Id != 0)
            {
                productVM.Product = _db.Product.Find(Id);
                if (productVM.Product != null)
                {
                    return View(productVM);
                }
                else
                {
                    return NotFound();
                }
            }
            return View(productVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Handle(ProductVM productVM)
        {

            if (ModelState.IsValid)
            {
                //圖片路徑
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _IWebHostEnviroment.WebRootPath;
                string upload = webRootPath + WC.ImagePath;
                string fileName = Guid.NewGuid().ToString();
                string extension = "";

                if (productVM.Product.Id == 0)//新增
                {
                    //處理圖片
                    if (files.Count > 0)
                    {
                         extension = Path.GetExtension(files[0].FileName);

                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }

                        productVM.Product.Images = fileName + extension;
                    }
                    _db.Product.Add(productVM.Product);
                }
                else //update 
                {
                    //取得原本資料
                    var objFromDb = _db.Product.AsNoTracking().FirstOrDefault(x => x.Id == productVM.Product.Id);
                    if (objFromDb != null)
                    {
                        //處理圖片
                        if (files.Count > 0)
                        {
                            extension = Path.GetExtension(files[0].FileName);
                            using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                            {
                                files[0].CopyTo(fileStream);
                            }
                            //刪除舊圖片
                            if (objFromDb.Images != null)
                            {
                                var oldFile = Path.Combine(upload, objFromDb.Images);
                                deleteImg(oldFile);
                            }
                            productVM.Product.Images = fileName + extension;//置入新路徑
                        }
                        else
                        {
                            productVM.Product.Images = objFromDb.Images;//回填舊路徑
                        }

                        _db.Product.Update(productVM.Product);
                    }
                }
            }

            //載入DropDown值
            productVM.CategoryDropDown = _db.Category.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            productVM.ApplicationDropDown = _db.Application.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            _db.SaveChanges();
            return View(productVM);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int? Id)
        {
            Product obj = _db.Product.Find(Id);
            if (obj != null)
            {
                if (obj.Images != null)
                {
                    deleteImg(obj.Images);
                }
                _db.Product.Remove(obj);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");

        }
        #endregion

        #region GenericFunction
        public bool deleteImg(string imgPath)
        {
            bool result = false;
            try
            {
                if (System.IO.File.Exists(imgPath))//刪除原有圖片
                {
                    System.IO.File.Delete(imgPath);
                }
                result = true;
            }
            catch { }
            return result;
        }
        #endregion
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Application" asp-action="Index">Application</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>